[project]
name = "llvm-project"
version = "1.0.0"
requires-python = ">=3.9"
dependencies = [
    "psutil>=5.9.4"
]

[project.optional-dependencies]
git = [
    "certifi==2024.8.30",
    "cffi==1.17.1",
    "charset-normalizer==3.3.2",
    "cryptography==43.0.1",
    "deprecated==1.2.14",
    "gitdb==4.0.11",
    "gitpython==3.1.43",
    "idna==3.8",
    "pycparser==2.22",
    "pygithub==2.2.0",
    "pyjwt[crypto]==2.9.0",
    "pynacl==1.5.0",
    "requests==2.32.3",
    "smmap==5.0.1",
    "typing-extensions==4.12.2",
    "urllib3==2.2.2",
    "wrapt==1.16.0",
]
docs = [
    "docutils==0.20.1",
    "furo==2024.1.29",
    "myst-parser==2.0.0",
    "recommonmark==0.7.1",
    "sphinx-automodapi==0.17.0",
    "sphinx-bootstrap-theme==0.8.1",
    "sphinx-markdown-tables==0.0.17",
    "sphinx==7.2.6",
    "sphinxcontrib-applehelp==1.0.8",
]
lldb-test = [
    "packaging>=24.1",
    "pexpect>=4.9.0 ; sys_platform != 'win32'",
]
formatting = [
    "black~=23.0",
    "darker==1.7.2",
    "pygithub==2.2.0",
]

[tool.black]
extend-exclude = '''
(
  third-party/
)
'''
